import type { Metadata } from "next";
import './globals.css';

import { Montserrat } from 'next/font/google';

import { ThemeProvider } from '@/provider/theme-provider';

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="bg-slate-700">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
